CREATE TABLE gix_dias_importados (
    tipo ENUM('clientes', 'notas'),
    data VARCHAR(10),
    erro TEXT NULL,
    PRIMARY KEY (tipo, data)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE gix_clientes (
    id INT(11),
    nome VARCHAR(255),
    cpfCnpj VARCHAR(255),
    tipoPessoa VARCHAR(255),
    telefone VARCHAR(255),
    celular VARCHAR(255),
    cep VARCHAR(20),
    email VARCHAR(255),
    endereco VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    pais VARCHAR(255),
    inscrEstadual VARCHAR(255),
    nomeReduzido VARCHAR(255),
    tipoCadastro VARCHAR(255),
    dataAtualizacao VARCHAR(10),
    tipoClienteCodigo VARCHAR(255),
    tipoClienteDescricao VARCHAR(255),
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE gix_nf_clientes (
    codigo INT(11),
    tipoPessoa VARCHAR(255),
    cnpjCpf VARCHAR(255),
    nome VARCHAR(255),
    celular VARCHAR(255),
    email VARCHAR(255),
    sexo VARCHAR(10),
    dataNascimento VARCHAR(10),
    profissao VARCHAR(255),
    dataCadastro VARCHAR(10),
    dataUltimaCompra VARCHAR(10),
    tipo VARCHAR(255),
    descricaoTipo VARCHAR(255),
    subTipo VARCHAR(255),
    descricaoSubTipo VARCHAR(255),
    endereco VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    estado VARCHAR(255),
    cep VARCHAR(20),
    complemento VARCHAR(255),
    PRIMARY KEY (codigo)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE gix_nf_produtos (
    id INT(11) AUTO_INCREMENT,
    idNf INT(11),
    numeroNf VARCHAR(255),
    codigoBarras VARCHAR(255),
    codigoInterno VARCHAR(255),
    codigoFabrica VARCHAR(255),
    codigoReferencia VARCHAR(255),
    descricao VARCHAR(255),
    precoUnitario DOUBLE,
    unidadeMedida VARCHAR(255),
    quantidade INT(11),
    descontoTotal DOUBLE,
    valorLiquido DOUBLE,
    valorIpi DOUBLE,
    valorST DOUBLE,
    valorFrete DOUBLE,
    valorSeguro DOUBLE,
    valorOutras DOUBLE,
    valorTotal DOUBLE,
    categoria VARCHAR(255),
    fabricante VARCHAR(255),
    marca VARCHAR(255),
    tipo VARCHAR(255),
    subtipo VARCHAR(255),
    subtipoDescricao VARCHAR(255),
    linha VARCHAR(255),
    linhaDescricao VARCHAR(255),
    familia VARCHAR(255),
    familiaDescricao VARCHAR(255),
    cor VARCHAR(255),
    corDescricao VARCHAR(255),
    exclusivoCd VARCHAR(255),
    situacao VARCHAR(255),
    fornecedor VARCHAR(255),
    operacao VARCHAR(255),
    PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE gix_nf_vendedores (
    codigo VARCHAR(255),
    cnpjCpf VARCHAR(255),
    nome VARCHAR(255),
    tipo VARCHAR(255),
    tipoDescricao VARCHAR(255),
    gerente VARCHAR(255),
    gerenteDescricao VARCHAR(255),
    ativoInativo VARCHAR(255),
    PRIMARY KEY (codigo)
) ENGINE = InnoDB DEFAULT CHARSET = latin1;

CREATE TABLE `gix_nf` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `empresaNota` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `empresaOrigem` VARCHAR(50) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `empresaNotaCodigo` INT(11) NULL DEFAULT NULL,
    `empresaOrigemCodigo` INT(11) NULL DEFAULT NULL,
    `clienteCodigo` INT(11) NULL DEFAULT NULL,
    `vendedorCodigo` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `data` VARCHAR(10) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `hora` TIME NULL DEFAULT NULL,
    `numeroNF` VARCHAR(255) NOT NULL COLLATE 'latin1_swedish_ci',
    `serieNF` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `condicaoPagamento` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `descricaoCondicaoPagamento` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `cartoes` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `chaveNFE` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `tipoNota` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `valorProdutos` DOUBLE NULL DEFAULT NULL,
    `valorDesconto` DOUBLE NULL DEFAULT NULL,
    `valorIPI` DOUBLE NULL DEFAULT NULL,
    `valorST` DOUBLE NULL DEFAULT NULL,
    `valorFrete` DOUBLE NULL DEFAULT NULL,
    `valorOutras` DOUBLE NULL DEFAULT NULL,
    `valorSeguro` DOUBLE NULL DEFAULT NULL,
    `numeroItens` INT(11) NULL DEFAULT NULL,
    `formaDePagamento` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `rentabilidadeTotal` VARCHAR(255) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
    `codigoPedido` INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE,
    UNIQUE INDEX `numeroNF` (`numeroNF`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = latin1;