export type GixInvoiceCustomer = {
    codigo: number;
    tipoPessoa: string;
    cnpjCpf: string;
    nome: string;
    celular: string;
    email: string;
    sexo: string;
    dataNascimento: string;
    profissao: string;
    dataCadastro: string;
    dataUltimaCompra: string;
    tipo: string;
    descricaoTipo: string;
    subTipo: string;
    descricaoSubTipo: string;
    endereco: string;
    bairro: string;
    cidade: string;
    estado: string;
    cep: string;
    complemento: string;
};